x-shared_environment: &shared_environment
  LOG_LEVEL: ${LOG_LEVEL:-debug}
  
services:
  clipboard-portal-server:
    container_name: clipboard-portal-server
    image: server:latest
    build:
      context: .
    environment:
      <<: *shared_environment
    ports:
      - "127.0.0.1:$PORT:8080" # host port : container port. Bind only locally to avoid exposing the service without Caddy
    volumes:
      - ./.env:/app/.env:ro
      - ./.env:/app/.env.production:ro
      - ./data:/app/data
    user: '0' # Run as root to avoid permission issues with host volumes
    command: ["serve", "--env", "production", "--hostname", "0.0.0.0", "--port", "8080"]
