x-shared_environment: &shared_environment
  LOG_LEVEL: ${LOG_LEVEL:-debug}
  
services:
  share-clipboard-server:
    container_name: share-clipboard-server
    image: server:latest
    build:
      context: .
    environment:
      <<: *shared_environment
    ports:
      - "127.0.0.1:$PORT:8080" # host port : container port. Bind only locally to avoid exposing the service without Caddy
    volumes:
      - ./.env:./App/.env
    # user: '0' # uncomment to run as root for testing purposes even though Dockerfile defines 'vapor' user.
    command: ["serve", "--env", "production", "--hostname", "0.0.0.0", "--port", "8080"]
